### PR TITLE
Addition: Canva processes page

### PR DESCRIPTION
**Pull request by kierisi**
I've created a section on pyOpenSci's use of [Canva](https://www.canva.com/) as a graphics platform, outlining what it's used for, and the processes surrounding Canva. I chose to place this section under the [Organization](https://www.pyopensci.org/handbook/organization/index.html) heading, as it feels process-based, but could also see it going under community, or potentially a new "pyOpenSci Brand" section. Let me know if you'd like me to change the location, and if there is any information related to Canva that I've missed!

### CODE REVIEW

**Comment by kierisi** [comment]
pre-commit.ci autofix

**Review by lwasser — CHANGES_REQUESTED** [review]
@kierisi i think this page needs a bit more love

1. let's pull our branding stuff and just focus on using canva
* pyos has a non profit pro plan for canva... 
* canva is an online platform that....  what is provides
* something about how canva handles copyright and that we can use all graphics under their copy right.  
* most assets in the pyOS ecosystem are created and stored in canva including our brand content 


* section about the brand content in canva and what we store there. 
* section about organization, folders and sharing folders with the pyos canva team 
* note: about stacking too many images in a single file -- hard to find

then finally permissions


* SECTION: who has access to canva
* process for adding someone to canva (and who we add)
* what happens when someone leaves (remove them from canva, etc)


notice that none of the above has anything to do with branding - it is all about how we use canva, what canva is, who has access, how we organize things,

**Comment by kierisi** [comment]
@lwasser I've made updates based on your feedback. since this page was essentially a re-write, I incorporated your suggestions beyond the initial bulleted list, but rolled them into entirely new text.

**Comment by kierisi** [comment]
pre-commit.ci autofix

**Comment by lwasser** [comment]
ok, @kierisi, I made some inline edits to the page. 

I: 
* removed my name and called out the ED as owner and admin, but any changes or questions about folder structure should be a team discussion in Slack. I like to write all docs as generic "this is how we operate" with a focus on roles not names. The only exception is our code of conduct team, which needs to specify people.
* clarified a few things
* added a TODO about adding a link to the off-boarding page once we have that in place.

please 
* give this one last read, 
*  make suggestions as you see fit
 
I'll  then approve, run the pre-commit bot, and merge.

**Review by lwasser — CHANGES_REQUESTED** [review]
one last review requested by you @kierisi  and then i'll merge

**Comment by kierisi** [comment]
pre-commit.ci autofix

**Comment by kierisi** [comment]
looks good to me! 

apologies for running the pre-commit bot. I didn't see that in your message until after I had run it. I had assumed I had forgotten to do it when I saw that it hadn't passed the check.

**Comment by lwasser** [comment]
> looks good to me!
> 
> Apologies for running the pre-commit bot. I didn't see that in your message until after I had run it. I had assumed I had forgotten to do it when I saw that it hadn't passed the check.

Thanks, @kierisi. Don't apologize! I only mentioned that because if we had more edits, we'd need to run it again anyway. but since you are good with it - you saved me from calling the bot again! I'll merge this now.

**Pull request merged**
