### PR TITLE
Corrected PR: added the PR checklist

### PR DESCRIPTION
**Pull request by kierisi**
this PR corrects the merge conflicts in #90 

the goal of this PR is to add a short checklist for users to follow when submitting a PR to pyOpenSci.

### CODE REVIEW

**Comment by kierisi** [comment]
pre-commit.ci autofix

**Comment by kierisi** [comment]
@lwasser this is ready for review, and should resolve the merge conflicts from #90, which I've closed with comment. I figured out what happened, and the fix was pretty straightforward. 

I've checked this PR for the correct files, and the local build looks good on my end as it incorporates this new information, but doesn't make any changes to the canva pages.

**Comment by lwasser** [comment]
awesome. thanks @kierisi i'll give this a review today!

**Review by lwasser — APPROVED** [review]

**Comment by lwasser** [comment]
pre-commit.ci autofix

**Pull request merged**
