### PR TITLE
feat: add translation processes

### PR DESCRIPTION
**Pull request by lwasser**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208768410555067

### CODE REVIEW

**Review by flpm — COMMENTED** [review]
Made two minor additions.

We should also consider adding a process to start a new language translation: if someone volunteers to work on a new language, who makes the go-ahead decision, designates the translation group/lead, etc. 

Back when I wrote the Translation guide for contributors I added a bit of information for the technical steps [here](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#starting-a-new-language-translation) but no other guidance.

**Comment by lwasser** [comment]
> Made two minor additions.
> 
> We should also consider adding a process to start a new language translation: if someone volunteers to work on a new language, who makes the go-ahead decision, designates the translation group/lead, etc.
> 
> Back when I wrote the Translation guide for contributors I added a bit of information for the technical steps [here](https://github.com/pyOpenSci/python-package-guide/blob/main/TRANSLATING.md#starting-a-new-language-translation) but no other guidance.

@flpm thank you for this! I'll create a new issue for that process for a new language. I think it's a great idea!

**Comment by lwasser** [comment]
ok, I'm going to merge this!! I opened #115 for a future pr where we create a process for someone who wants to start working on a new language translation

**Comment by lwasser** [comment]
pre-commit autofix

**Comment by lwasser** [comment]
pre-commit.ci autofix

**Comment by lwasser** [comment]
Ok merging this. i will sort out the font issues in a separate pr!

**Pull request merged**
